apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: wordpress-operator
  template:
    metadata:
      labels:
        name: wordpress-operator
    spec:
      serviceAccountName: wordpress-operator
      containers:
        - name: wordpress-operator
          image: quay.io/srust/wordpress-operator:better
          command:
          - wordpress-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "wordpress-operator"
            - name: WORDPRESS_SECRET_NAME
              value: "mysql-pass"
            - name: WORDPRESS_SECRET_KEY
              value: "password"
            - name: WORDPRESS_PVC_SIZE
              value: "20Gi"
            - name: WORDPRESS_IMAGE_MYSQL
              value: "mysql:5.6"
            - name: WORDPRESS_IMAGE_WORDPRESS
              value: "wordpress:4.8-apache"
